apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment 
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: worker 
  template: 
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker 
          image: maaverik1/fib-worker
     
# the worker pod doesn't need anything to be connected to it, it connects to redis itself,
# so it doesn't need exposed ports or a Service of its own