language: generic

sudo: required

services:
  - docker

before_install:
  # we'll use dev dockerfile for client since it's the only one that has a test 
  # and only dev version comes with a test server
  # the last arg in the below command is the build context, i.e., the directory with files to build
  - docker build -t maaverik1/fib-client-test -f ./client/Dockerfile.dev ./client

# add test commands here
script:
  # the below command runs the test and then exits with exit code 0 if test ran successfully
  - docker run -e CI=true maaverik1/fib-client-test npm test

after_success:
  - docker build -t maaverik1/fib-client ./client
  - docker build -t maaverik1/fib-server ./server
  - docker build -t maaverik1/fib-worker ./worker
  - docker build -t maaverik1/fib-nginx ./nginx

  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push images to docker hub
  - docker push maaverik1/fib-client
  - docker push maaverik1/fib-server
  - docker push maaverik1/fib-worker
  - docker push maaverik1/fib-nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-115909680305'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
