version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev 
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - '4000:80'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=pg_password # specify without value to get value from OS environment variable
  redis:
    image: 'redis:latest'
  api:
    build: 
      dockerfile: Dockerfile.dev 
      context: ./server
    volumes: 
      - /app/node_modules   # don't try to redirect this folder to mounted volume
      - ./server:/app       # redirect everything else in /app to /server
    environment:
      - REDIS_HOST=redis    # the service name acts as hostname so this points to URI of redis container
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=pg_password
      - PGPORT=5432
  client:
    stdin_open: true
    build: 
      dockerfile: Dockerfile.dev 
      context: ./client
    volumes:
      - /home/node/app/node_modules 
      - ./client:/home/node/app 
  worker:
    build: 
      dockerfile: Dockerfile.dev 
      context: ./worker
    volumes:
      - /app/node_modules 
      - ./worker:/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
